In [1]:
import pandas as pd
import boto3
from io import StringIO

In [2]:
# Initialize s3 client
s3_client = boto3.client('s3')

# Get object from s3 bucket
response = s3_client.get_object(Bucket="sagemaker-us-east-1-237863594148", 
                                Key="data-preprocessing/information-extraction.csv")

# Read csv content
csv_content = response['Body'].read().decode('utf-8')

# Convert to dataframe
df = pd.read_csv(StringIO(csv_content))

df.head(10)

,alumni_id,graduation_year,degree_type,total_jobs,job_titles,job_companies,technologies_used,tools_used,daen_program_courses,daen_program_technologies,daen_program_tools,daen_program_rating,daen_program_valuable_skills,daen_program_potential_improvement,course_certification_completed
0,CEC-DAEN-2019-MS-1,2019,MS,3,Data Scientist,"C&M Associates, Choice Hotels International","Python, R, SQL, AWS","MS Excel, CUBE, ESRI, ArcGIS",DAEN690,"R, SQL","Machine Learning, Scripting, Data Wrangling",3,"Programming, Data Wrangling, SQL, Machine Lear...","Python, Cloud, Data Engineering, Docker, Model...",NaN
1,CEC-DAEN-2019-MS-2,2019,MS,4,"Data Engineer, Machine Learning Engineer","Fannie Mae, Activision Blizzard Media","Python, GCP, Docker, BigQuery","Evidently AI, Looker Studio, MS Excel, Do it, ...","OR604, STAT515, Database",NaN,"Database Systems, Statistical Analysis, Linear...","3.5, 4","Linear Programming, Optimization, Statistical ...","Earlier Longer DAEN Capstone Project, Project ...","Team Communication LinkedIn Course, Project Ma..."
2,CEC-DAEN-2019-MS-3,2019,MS,4,"Data Analyst, Data Scientist","Databuoy Corp, Ashling Partners","AWS, Python, Redis, MS Azure, OpenAI, MS SQL S...","ArcGIS, MS Power BI, Fishbowl, UiPath, MS Powe...","GBUS738, AIT580, GBUS739, GBUS720, GBUS721, GB...","AWS, NoSQL","MS Power BI, IBM SPSS, RapidMiner, SAS Enterpr...",3,"Data Modeling, Statistics, Fraud Examination, ...","Deep Learning, AIT Courses, Cloud","Indico Data, UIpath, AWS Data Scientist, Azure..."
3,CEC-DAEN-2020-MS-1,2020,MS,3,"Software Engineer, Account Strategist","Genius Plaza, Potomac Economics, Market Star","Python, SQL, Django, JavaScript, React","Google Analytics, Tableau, MS Power BI","Natural Language Processing, Operations Resear...",NaN,"NLP, XGBoost, Naive Bayes",4,"Data Analysis, Sentiment Analysis, Data Prepar...","Cloud, AI Ethics, Hands-on Projects, Real-worl...",Google Project Management
4,CEC-DAEN-2020-MS-2,2020,MS,2,"Data Analyst, Data Analytics Engineer","Verizon, Association Analytics","SQL, Python, AWS, Databricks, ELK stack","GitHub, Jira, Kibana",Data Mining,"SQL, R",NaN,4,"Data Analysis, Data Transformation, SQL","Cloud, GitHub, Version Control, Hands-on Projects",DBT training for analytics engineer
5,CEC-DAEN-2020-MS-3,2020,MS,2,"Data Scientist, Data Analyst",Comscore,"Python, SQL, Spark, AWS, Hadoop, Snowflake","Zeppelin, MS Power BI","STAT515, OR568, AIT580, AIT690, AID726, OR531,...","R, Python","Statistical Analysis, NLP, Machine Learning",5,"Statistical Analysis, Business Decision Making...","Machine Learning, AI",NaN
6,CEC-DAEN-2020-MS-4,2020,MS,1,Data Analyst,FINRA,"SQL, AWS","IBM Cognos, Microstrategy, MS Power BI, Grafa...","Data Visualization, Data Warehousing, DAEN698,...",NaN,"Python Libraries, Data Wrangling, Tableau","3.5, 4","Statistics, Data Warehousing, Data Modeling, P...","Course Selection Options, Statistics, Math",NaN
7,CEC-DAEN-2020-MS-5,2020,MS,1,Data Analyst,Codice,"SQL, Python","Tableau, MS Excel, SAS","Operations Statistics, Database, Advanced Stat...","R, Python, SQL",NaN,3,"Statistics, Database, Data Mining, Statistical...","Tableau, Enterprise-level Visualization Tools,...",Financial Modeling of Data from Wharton Online
8,CEC-DAEN-2021-MS-1,2021,MS,2,Data Engineer,National Hockey League,"Python, SQL, Spark, AWS, Kafka, Snowflake",ETL,"Database, Excel analytics",Python,"MS Excel, Database Systems",4,"Data Loading, Data Transformation, Real-world ...","Hands-on Projects, Python, Practical Application","Snowflake Snow Pro Core Certification, Snowfla..."
9,CEC-DAEN-2021-MS-2,2021,MS,2,Data Analyst,"CloudNova Technology, LLC","Python, SQL, NoSQL, Java, Linux, Elasticsearch...","Tableau, Kibana, Jira, Bitbucket","Database, Market Research","SQL, NoSQL",Database Systems,4,"Database, Dashboard Creation, Requirements Gat...","Cloud, Hands-on Projects, Big Data, Tableau","Tableau Desktop Specialist, PMP certification,..."

In [3]:
# Function to clean and split strings
def clean_and_split_string(value):
    # Handle empty cells
    if pd.isna(value) or value == 'nan' or value == '':
        return []
    
    # Handle newlines and clean the string
    value = value.replace('\n', ', ')
    
    # Split by comma and clean each item
    return [item.strip() for item in value.split(',') if item.strip() and item.lower() != 'nan']
    
df.head(10)

,alumni_id,graduation_year,degree_type,total_jobs,job_titles,job_companies,technologies_used,tools_used,daen_program_courses,daen_program_technologies,daen_program_tools,daen_program_rating,daen_program_valuable_skills,daen_program_potential_improvement,course_certification_completed
0,CEC-DAEN-2019-MS-1,2019,MS,3,Data Scientist,"C&M Associates, Choice Hotels International","Python, R, SQL, AWS","MS Excel, CUBE, ESRI, ArcGIS",DAEN690,"R, SQL","Machine Learning, Scripting, Data Wrangling",3,"Programming, Data Wrangling, SQL, Machine Lear...","Python, Cloud, Data Engineering, Docker, Model...",NaN
1,CEC-DAEN-2019-MS-2,2019,MS,4,"Data Engineer, Machine Learning Engineer","Fannie Mae, Activision Blizzard Media","Python, GCP, Docker, BigQuery","Evidently AI, Looker Studio, MS Excel, Do it, ...","OR604, STAT515, Database",NaN,"Database Systems, Statistical Analysis, Linear...","3.5, 4","Linear Programming, Optimization, Statistical ...","Earlier Longer DAEN Capstone Project, Project ...","Team Communication LinkedIn Course, Project Ma..."
2,CEC-DAEN-2019-MS-3,2019,MS,4,"Data Analyst, Data Scientist","Databuoy Corp, Ashling Partners","AWS, Python, Redis, MS Azure, OpenAI, MS SQL S...","ArcGIS, MS Power BI, Fishbowl, UiPath, MS Powe...","GBUS738, AIT580, GBUS739, GBUS720, GBUS721, GB...","AWS, NoSQL","MS Power BI, IBM SPSS, RapidMiner, SAS Enterpr...",3,"Data Modeling, Statistics, Fraud Examination, ...","Deep Learning, AIT Courses, Cloud","Indico Data, UIpath, AWS Data Scientist, Azure..."
3,CEC-DAEN-2020-MS-1,2020,MS,3,"Software Engineer, Account Strategist","Genius Plaza, Potomac Economics, Market Star","Python, SQL, Django, JavaScript, React","Google Analytics, Tableau, MS Power BI","Natural Language Processing, Operations Resear...",NaN,"NLP, XGBoost, Naive Bayes",4,"Data Analysis, Sentiment Analysis, Data Prepar...","Cloud, AI Ethics, Hands-on Projects, Real-worl...",Google Project Management
4,CEC-DAEN-2020-MS-2,2020,MS,2,"Data Analyst, Data Analytics Engineer","Verizon, Association Analytics","SQL, Python, AWS, Databricks, ELK stack","GitHub, Jira, Kibana",Data Mining,"SQL, R",NaN,4,"Data Analysis, Data Transformation, SQL","Cloud, GitHub, Version Control, Hands-on Projects",DBT training for analytics engineer
5,CEC-DAEN-2020-MS-3,2020,MS,2,"Data Scientist, Data Analyst",Comscore,"Python, SQL, Spark, AWS, Hadoop, Snowflake","Zeppelin, MS Power BI","STAT515, OR568, AIT580, AIT690, AID726, OR531,...","R, Python","Statistical Analysis, NLP, Machine Learning",5,"Statistical Analysis, Business Decision Making...","Machine Learning, AI",NaN
6,CEC-DAEN-2020-MS-4,2020,MS,1,Data Analyst,FINRA,"SQL, AWS","IBM Cognos, Microstrategy, MS Power BI, Grafa...","Data Visualization, Data Warehousing, DAEN698,...",NaN,"Python Libraries, Data Wrangling, Tableau","3.5, 4","Statistics, Data Warehousing, Data Modeling, P...","Course Selection Options, Statistics, Math",NaN
7,CEC-DAEN-2020-MS-5,2020,MS,1,Data Analyst,Codice,"SQL, Python","Tableau, MS Excel, SAS","Operations Statistics, Database, Advanced Stat...","R, Python, SQL",NaN,3,"Statistics, Database, Data Mining, Statistical...","Tableau, Enterprise-level Visualization Tools,...",Financial Modeling of Data from Wharton Online
8,CEC-DAEN-2021-MS-1,2021,MS,2,Data Engineer,National Hockey League,"Python, SQL, Spark, AWS, Kafka, Snowflake",ETL,"Database, Excel analytics",Python,"MS Excel, Database Systems",4,"Data Loading, Data Transformation, Real-world ...","Hands-on Projects, Python, Practical Application","Snowflake Snow Pro Core Certification, Snowfla..."
9,CEC-DAEN-2021-MS-2,2021,MS,2,Data Analyst,"CloudNova Technology, LLC","Python, SQL, NoSQL, Java, Linux, Elasticsearch...","Tableau, Kibana, Jira, Bitbucket","Database, Market Research","SQL, NoSQL",Database Systems,4,"Database, Dashboard Creation, Requirements Gat...","Cloud, Hands-on Projects, Big Data, Tableau","Tableau Desktop Specialist, PMP certification,..."

In [4]:
# Function to process ratings
def process_rating(value):
    
    if pd.isna(value) or value == 'nan' or value == '':
        return value
    
    # Split and clean the ratings
    ratings = clean_and_split_string(str(value))
    
    if not ratings:
        return value
    
    # Convert to numbers and calculate average if multiple values exist
    try:
        numeric_ratings = [float(r) for r in ratings]
        return sum(numeric_ratings) / len(numeric_ratings) if len(numeric_ratings) > 0 else value
    except ValueError:
        return value

# Process ratings column first
if 'daen_program_rating' in df.columns:
    df['daen_program_rating'] = df['daen_program_rating'].apply(process_rating)
    
df.head(10)

,alumni_id,graduation_year,degree_type,total_jobs,job_titles,job_companies,technologies_used,tools_used,daen_program_courses,daen_program_technologies,daen_program_tools,daen_program_rating,daen_program_valuable_skills,daen_program_potential_improvement,course_certification_completed
0,CEC-DAEN-2019-MS-1,2019,MS,3,Data Scientist,"C&M Associates, Choice Hotels International","Python, R, SQL, AWS","MS Excel, CUBE, ESRI, ArcGIS",DAEN690,"R, SQL","Machine Learning, Scripting, Data Wrangling",3.00,"Programming, Data Wrangling, SQL, Machine Lear...","Python, Cloud, Data Engineering, Docker, Model...",NaN
1,CEC-DAEN-2019-MS-2,2019,MS,4,"Data Engineer, Machine Learning Engineer","Fannie Mae, Activision Blizzard Media","Python, GCP, Docker, BigQuery","Evidently AI, Looker Studio, MS Excel, Do it, ...","OR604, STAT515, Database",NaN,"Database Systems, Statistical Analysis, Linear...",3.75,"Linear Programming, Optimization, Statistical ...","Earlier Longer DAEN Capstone Project, Project ...","Team Communication LinkedIn Course, Project Ma..."
2,CEC-DAEN-2019-MS-3,2019,MS,4,"Data Analyst, Data Scientist","Databuoy Corp, Ashling Partners","AWS, Python, Redis, MS Azure, OpenAI, MS SQL S...","ArcGIS, MS Power BI, Fishbowl, UiPath, MS Powe...","GBUS738, AIT580, GBUS739, GBUS720, GBUS721, GB...","AWS, NoSQL","MS Power BI, IBM SPSS, RapidMiner, SAS Enterpr...",3.00,"Data Modeling, Statistics, Fraud Examination, ...","Deep Learning, AIT Courses, Cloud","Indico Data, UIpath, AWS Data Scientist, Azure..."
3,CEC-DAEN-2020-MS-1,2020,MS,3,"Software Engineer, Account Strategist","Genius Plaza, Potomac Economics, Market Star","Python, SQL, Django, JavaScript, React","Google Analytics, Tableau, MS Power BI","Natural Language Processing, Operations Resear...",NaN,"NLP, XGBoost, Naive Bayes",4.00,"Data Analysis, Sentiment Analysis, Data Prepar...","Cloud, AI Ethics, Hands-on Projects, Real-worl...",Google Project Management
4,CEC-DAEN-2020-MS-2,2020,MS,2,"Data Analyst, Data Analytics Engineer","Verizon, Association Analytics","SQL, Python, AWS, Databricks, ELK stack","GitHub, Jira, Kibana",Data Mining,"SQL, R",NaN,4.00,"Data Analysis, Data Transformation, SQL","Cloud, GitHub, Version Control, Hands-on Projects",DBT training for analytics engineer
5,CEC-DAEN-2020-MS-3,2020,MS,2,"Data Scientist, Data Analyst",Comscore,"Python, SQL, Spark, AWS, Hadoop, Snowflake","Zeppelin, MS Power BI","STAT515, OR568, AIT580, AIT690, AID726, OR531,...","R, Python","Statistical Analysis, NLP, Machine Learning",5.00,"Statistical Analysis, Business Decision Making...","Machine Learning, AI",NaN
6,CEC-DAEN-2020-MS-4,2020,MS,1,Data Analyst,FINRA,"SQL, AWS","IBM Cognos, Microstrategy, MS Power BI, Grafa...","Data Visualization, Data Warehousing, DAEN698,...",NaN,"Python Libraries, Data Wrangling, Tableau",3.75,"Statistics, Data Warehousing, Data Modeling, P...","Course Selection Options, Statistics, Math",NaN
7,CEC-DAEN-2020-MS-5,2020,MS,1,Data Analyst,Codice,"SQL, Python","Tableau, MS Excel, SAS","Operations Statistics, Database, Advanced Stat...","R, Python, SQL",NaN,3.00,"Statistics, Database, Data Mining, Statistical...","Tableau, Enterprise-level Visualization Tools,...",Financial Modeling of Data from Wharton Online
8,CEC-DAEN-2021-MS-1,2021,MS,2,Data Engineer,National Hockey League,"Python, SQL, Spark, AWS, Kafka, Snowflake",ETL,"Database, Excel analytics",Python,"MS Excel, Database Systems",4.00,"Data Loading, Data Transformation, Real-world ...","Hands-on Projects, Python, Practical Application","Snowflake Snow Pro Core Certification, Snowfla..."
9,CEC-DAEN-2021-MS-2,2021,MS,2,Data Analyst,"CloudNova Technology, LLC","Python, SQL, NoSQL, Java, Linux, Elasticsearch...","Tableau, Kibana, Jira, Bitbucket","Database, Market Research","SQL, NoSQL",Database Systems,4.00,"Database, Dashboard Creation, Requirements Gat...","Cloud, Hands-on Projects, Big Data, Tableau","Tableau Desktop Specialist, PMP certification,..."

In [5]:
# List of columns that contain comma-separated values
columns_to_split = ['job_titles', 'job_companies', 'technologies_used', 'tools_used', 
                   'daen_program_courses', 'daen_program_tools', 
                    'daen_program_technologies', 'daen_program_valuable_skills',
                    'daen_program_potential_improvement', 'course_certification_completed']

# Function to get maximum count of items in a column
def get_max_count(series):
    return max(len(clean_and_split_string(x)) for x in series)

# Function to split a value into a list of specified length
def split_to_fixed_length(value, max_length):
    items = clean_and_split_string(value)
    # Pad with none if needed
    return items + [None] * (max_length - len(items))

# Create new dataframe for results
result_df = df.copy()

# Process each column
for col in columns_to_split:
    if col in df.columns:
        # Get maximum count for this column
        max_count = get_max_count(df[col])
        print(f"Maximum items in {col}: {max_count}")
        
        # Generate new columns for this field
        for i in range(max_count):
            col_name = f"{col}_{i+1}"
            result_df[col_name] = df[col].apply(lambda x: split_to_fixed_length(x, max_count)[i])
        
        # Drop original column
        result_df = result_df.drop(columns=[col])

print("\nTransformed shape:", result_df.shape)
with pd.option_context('display.max_columns', None, 'display.max_rows', None):
    print(result_df.head(10))
result_df.head(10)

# Verify no columns contain comma-delimited values
def check_remaining_commas(df):
    issues = []
    for column in df.columns:
        mask = df[column].astype(str).str.contains(',', na=False)
        if mask.any():
            print(f"\nProblematic values in {column}:")
            problem_rows = df[mask]
            for idx, row in problem_rows.iterrows():
                print(f"Row {idx}: {row[column]}")
            issues.append(f"Column '{column}' still contains commas in rows: {list(df[mask].index)}")
    return issues

# Check for any remaining issues
issues = check_remaining_commas(result_df)
if issues:
    print("\nWarning: Found remaining comma-delimited values:")
    for issue in issues:
        print(issue)
else:
    print("\nSuccess: No comma-delimited values remain in any column")

# Display column names to see the new structure
print("\nNew column names:")
display(result_df.columns.tolist())

Maximum items in job_titles: 2
Maximum items in job_companies: 3
Maximum items in technologies_used: 13
Maximum items in tools_used: 8
Maximum items in daen_program_courses: 7
Maximum items in daen_program_tools: 4
Maximum items in daen_program_technologies: 4
Maximum items in daen_program_valuable_skills: 6
Maximum items in daen_program_potential_improvement: 6
Maximum items in course_certification_completed: 4

Transformed shape: (14, 62)
             alumni_id  graduation_year degree_type  total_jobs  \
0   CEC-DAEN-2019-MS-1             2019          MS           3
1   CEC-DAEN-2019-MS-2             2019          MS           4
2   CEC-DAEN-2019-MS-3             2019          MS           4
3  CEC-DAEN-2020-MS-1              2020          MS           3
4   CEC-DAEN-2020-MS-2             2020          MS           2
5   CEC-DAEN-2020-MS-3             2020          MS           2
6   CEC-DAEN-2020-MS-4             2020          MS           1
7   CEC-DAEN-2020-MS-5             2020          MS           1
8   CEC-DAEN-2021-MS-1             2021          MS           2
9   CEC-DAEN-2021-MS-2             2021          MS           2

   daen_program_rating       job_titles_1               job_titles_2  \
0                 3.00     Data Scientist                       None
1                 3.75      Data Engineer  Machine Learning Engineer
2                 3.00       Data Analyst             Data Scientist
3                 4.00  Software Engineer         Account Strategist
4                 4.00       Data Analyst    Data Analytics Engineer
5                 5.00     Data Scientist               Data Analyst
6                 3.75       Data Analyst                       None
7                 3.00       Data Analyst                       None
8                 4.00      Data Engineer                       None
9                 4.00       Data Analyst                       None

          job_companies_1              job_companies_2 job_companies_3  \
0          C&M Associates  Choice Hotels International            None
1              Fannie Mae    Activision Blizzard Media            None
2           Databuoy Corp             Ashling Partners            None
3            Genius Plaza            Potomac Economics     Market Star
4                 Verizon        Association Analytics            None
5                Comscore                         None            None
6                   FINRA                         None            None
7                  Codice                         None            None
8  National Hockey League                         None            None
9    CloudNova Technology                          LLC            None

  technologies_used_1 technologies_used_2 technologies_used_3  \
0              Python                   R                 SQL
1              Python                 GCP              Docker
2                 AWS              Python               Redis
3              Python                 SQL              Django
4                 SQL              Python                 AWS
5              Python                 SQL               Spark
6                 SQL                 AWS                None
7                 SQL              Python                None
8              Python                 SQL               Spark
9              Python                 SQL               NoSQL

  technologies_used_4 technologies_used_5 technologies_used_6  \
0                 AWS                None                None
1            BigQuery                None                None
2            MS Azure              OpenAI       MS SQL Server
3          JavaScript               React                None
4          Databricks           ELK stack                None
5                 AWS              Hadoop           Snowflake
6                None                None                None
7                None                None                None
8                 AWS               Kafka           Snowflake
9                Java               Linux       Elasticsearch

  technologies_used_7 technologies_used_8 technologies_used_9  \
0                None                None                None
1                None                None                None
2          PostgreSQL           OracleSQL           Snowflake
3                None                None                None
4                None                None                None
5                None                None                None
6                None                None                None
7                None                None                None
8                None                None                None
9                 AWS             MongoDB          PostgreSQL

  technologies_used_10 technologies_used_11 technologies_used_12  \
0                 None                 None                 None
1                 None                 None                 None
2           Databricks            LangChain           Llamaindex
3                 None                 None                 None
4                 None                 None                 None
5                 None                 None                 None
6                 None                 None                 None
7                 None                 None                 None
8                 None                 None                 None
9                 None                 None                 None

  technologies_used_13      tools_used_1   tools_used_2 tools_used_3  \
0                 None          MS Excel           CUBE         ESRI
1                 None      Evidently AI  Looker Studio     MS Excel
2                  GCP            ArcGIS    MS Power BI     Fishbowl
3                 None  Google Analytics        Tableau  MS Power BI
4                 None            GitHub           Jira       Kibana
5                 None          Zeppelin    MS Power BI         None
6                 None        IBM Cognos  Microstrategy  MS Power BI
7                 None           Tableau       MS Excel          SAS
8                 None               ETL           None         None
9                 None           Tableau         Kibana         Jira

  tools_used_4     tools_used_5        tools_used_6 tools_used_7 tools_used_8  \
0       ArcGIS             None                None         None         None
1        Do it  Shell Scripting  Linear Programming         None         None
2       UiPath         MS Power          TensorFlow      PyAudio        Pydub
3         None             None                None         None         None
4         None             None                None         None         None
5         None             None                None         None         None
6      Grafana           Splunk                None         None         None
7         None             None                None         None         None
8         None             None                None         None         None
9    Bitbucket             None                None         None         None

        daen_program_courses_1 daen_program_courses_2 daen_program_courses_3  \
0                      DAEN690                   None                   None
1                        OR604                STAT515               Database
2                      GBUS738                 AIT580                GBUS739
3  Natural Language Processing    Operations Research            Data Mining
4                  Data Mining                   None                   None
5                      STAT515                  OR568                 AIT580
6           Data Visualization       Data Warehousing                DAEN698
7        Operations Statistics               Database    Advanced Statistics
8                     Database        Excel analytics                   None
9                     Database        Market Research                   None

  daen_program_courses_4 daen_program_courses_5 daen_program_courses_6  \
0                   None                   None                   None
1                   None                   None                   None
2                GBUS720                GBUS721                GBUS744
3                   None                   None                   None
4                   None                   None                   None
5                 AIT690                 AID726                  OR531
6                DAEN690                   None                   None
7            Data Mining                   None                   None
8                   None                   None                   None
9                   None                   None                   None

  daen_program_courses_7  daen_program_tools_1  daen_program_tools_2  \
0                   None      Machine Learning             Scripting
1                   None      Database Systems  Statistical Analysis
2                DAEN690           MS Power BI              IBM SPSS
3                   None                   NLP               XGBoost
4                   None                  None                  None
5                 AID582  Statistical Analysis                   NLP
6                   None      Python Libraries        Data Wrangling
7                   None                  None                  None
8                   None              MS Excel      Database Systems
9                   None      Database Systems                  None

  daen_program_tools_3  daen_program_tools_4 daen_program_technologies_1  \
0       Data Wrangling                  None                           R
1   Linear Programming                  None                        None
2           RapidMiner  SAS Enterprise Miner                         AWS
3          Naive Bayes                  None                        None
4                 None                  None                         SQL
5     Machine Learning                  None                           R
6              Tableau                  None                        None
7                 None                  None                           R
8                 None                  None                      Python
9                 None                  None                         SQL

  daen_program_technologies_2 daen_program_technologies_3  \
0                         SQL                        None
1                        None                        None
2                       NoSQL                        None
3                        None                        None
4                           R                        None
5                      Python                        None
6                        None                        None
7                      Python                         SQL
8                        None                        None
9                       NoSQL                        None

  daen_program_technologies_4 daen_program_valuable_skills_1  \
0                        None                    Programming
1                        None             Linear Programming
2                        None                  Data Modeling
3                        None                  Data Analysis
4                        None                  Data Analysis
5                        None           Statistical Analysis
6                        None                     Statistics
7                        None                     Statistics
8                        None                   Data Loading
9                        None                       Database

  daen_program_valuable_skills_2 daen_program_valuable_skills_3  \
0                 Data Wrangling                            SQL
1                   Optimization           Statistical Analysis
2                     Statistics              Fraud Examination
3             Sentiment Analysis               Data Preparation
4            Data Transformation                            SQL
5       Business Decision Making                     NLP Models
6               Data Warehousing                  Data Modeling
7                       Database                    Data Mining
8            Data Transformation                Real-world Data
9             Dashboard Creation         Requirements Gathering

  daen_program_valuable_skills_4 daen_program_valuable_skills_5  \
0               Machine Learning                           None
1      Statistical Visualization                       Database
2   Financial Statement Analysis         Asset Misappropriation
3                  Data Modeling        Monte Carlo Simulations
4                           None                           None
5                     LLM Models                  Data Modeling
6   Principal Component Analysis                 Data Wrangling
7           Statistical Modeling                           None
8               Data Preparation                  Data Cleaning
9                  Data Workflow                           None

  daen_program_valuable_skills_6  daen_program_potential_improvement_1  \
0                           None                                Python
1            Feature Engineering  Earlier Longer DAEN Capstone Project
2        Account Reconciliations                         Deep Learning
3                       MS Excel                                 Cloud
4                           None                                 Cloud
5           Statistical Modeling                      Machine Learning
6                         Python              Course Selection Options
7                           None                               Tableau
8                       MS Excel                     Hands-on Projects
9                           None                                 Cloud

   daen_program_potential_improvement_2 daen_program_potential_improvement_3  \
0                                 Cloud                     Data Engineering
1                      Project Planning                   Project Management
2                           AIT Courses                                Cloud
3                             AI Ethics                    Hands-on Projects
4                                GitHub                      Version Control
5                                    AI                                 None
6                            Statistics                                 Math
7  Enterprise-level Visualization Tools                    Hands-on Projects
8                                Python                Practical Application
9                     Hands-on Projects                             Big Data

  daen_program_potential_improvement_4 daen_program_potential_improvement_5  \
0                               Docker                     Model Deployment
1                        ML Operations                Production Deployment
2                                 None                                 None
3         Real-world Business Problems      Interdisciplinary Collaboration
4                    Hands-on Projects                                 None
5                                 None                                 None
6                                 None                                 None
7                Business Intelligence                                 None
8                                 None                                 None
9                              Tableau                                 None

  daen_program_potential_improvement_6  \
0                Practical Application
1                                Cloud
2                                 None
3              Industry Collaborations
4                                 None
5                                 None
6                                 None
7                                 None
8                                 None
9                                 None

                 course_certification_completed_1  \
0                                            None
1              Team Communication LinkedIn Course
2                                     Indico Data
3                       Google Project Management
4             DBT training for analytics engineer
5                                            None
6                                            None
7  Financial Modeling of Data from Wharton Online
8           Snowflake Snow Pro Core Certification
9                      Tableau Desktop Specialist

             course_certification_completed_2  \
0                                        None
1          Project Management LinkedIn Course
2                                      UIpath
3                                        None
4                                        None
5                                        None
6                                        None
7                                        None
8  Snowflake Advanced Architect Certification
9                           PMP certification

   course_certification_completed_3 course_certification_completed_4
0                              None                             None
1                              None                             None
2                AWS Data Scientist             Azure Data Scientist
3                              None                             None
4                              None                             None
5                              None                             None
6                              None                             None
7                              None                             None
8                              None                             None
9  ISME Security Awareness Training                             None

Success: No comma-delimited values remain in any column

New column names:

['alumni_id',
 'graduation_year',
 'degree_type',
 'total_jobs',
 'daen_program_rating',
 'job_titles_1',
 'job_titles_2',
 'job_companies_1',
 'job_companies_2',
 'job_companies_3',
 'technologies_used_1',
 'technologies_used_2',
 'technologies_used_3',
 'technologies_used_4',
 'technologies_used_5',
 'technologies_used_6',
 'technologies_used_7',
 'technologies_used_8',
 'technologies_used_9',
 'technologies_used_10',
 'technologies_used_11',
 'technologies_used_12',
 'technologies_used_13',
 'tools_used_1',
 'tools_used_2',
 'tools_used_3',
 'tools_used_4',
 'tools_used_5',
 'tools_used_6',
 'tools_used_7',
 'tools_used_8',
 'daen_program_courses_1',
 'daen_program_courses_2',
 'daen_program_courses_3',
 'daen_program_courses_4',
 'daen_program_courses_5',
 'daen_program_courses_6',
 'daen_program_courses_7',
 'daen_program_tools_1',
 'daen_program_tools_2',
 'daen_program_tools_3',
 'daen_program_tools_4',
 'daen_program_technologies_1',
 'daen_program_technologies_2',
 'daen_program_technologies_3',
 'daen_program_technologies_4',
 'daen_program_valuable_skills_1',
 'daen_program_valuable_skills_2',
 'daen_program_valuable_skills_3',
 'daen_program_valuable_skills_4',
 'daen_program_valuable_skills_5',
 'daen_program_valuable_skills_6',
 'daen_program_potential_improvement_1',
 'daen_program_potential_improvement_2',
 'daen_program_potential_improvement_3',
 'daen_program_potential_improvement_4',
 'daen_program_potential_improvement_5',
 'daen_program_potential_improvement_6',
 'course_certification_completed_1',
 'course_certification_completed_2',
 'course_certification_completed_3',
 'course_certification_completed_4']

In [6]:
# Save expanded data
result_df.to_csv('preprocessed-information-extraction.csv', index=False)